name: Create Branch
on: 
  workflow_dispatch:
jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Creating Organization Repository
    steps:      
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'Test1'
          sha: '${{ github.event.pull_request.head.sha }}'          
