name: Create Repo
on: 
  workflow_dispatch:
    inputs:
      repo-name: 
        description: 'Name of the repository to be created'
        required: true
        default: 'WorkFlowTestRepo1'

jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Creating Organization Repository
    steps:      
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v3.0.0          
